[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ido = "DoK1DNxEDNA69r9849ZkDuoJt1Pz39rZ5qwgaqPykLXH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
